street_furniture.csv

In [99]:
import pandas as pd

path = "street_furniture.csv"
furn = pd.read_csv(path)

furn.head()

,GIS_ID,DESCRIPTION,ASSET_CLASS,ASSET_TYPE,MODEL_NO,MODEL_DESCR,DIVISION,COMPANY,LOCATION_DESC,CONDITION_RATING,EVALUATION_DATE,EASTING,NORTHING,UploadDate,CoordinateLocation
0,1078671,Floral Crate/Planter Box - Granite Tree Plante...,Outdoor Furniture,Floral Crate/Planter Box,200601-001,Floral Crate/Planter Box - Granite Tree Plante...,Infrastructure and Assets,City of Melbourne,Bourke Street between Swanston Street and Eliz...,3.45,2021-04-30,320850.60,5812901.23,2021-08-14,"-37.8137229993323, 144.9647568363893"
1,1084271,Bollard - Timber Bollard,Outdoor Furniture,Bollard,200401-067,Bollard - Timber Bollard,Infrastructure and Assets,City of Melbourne,St Kilda Road between Armadale Street and Comm...,2.85,2021-04-30,322159.31,5809533.16,2021-08-14,"-37.8443169308817, 144.9787883061352"
2,1078893,Seat - Stainless Steel Straight Seat,Outdoor Furniture,Seat,201101-027,Seat - Stainless Steel Straight Seat,Infrastructure and Assets,City of Melbourne,Bourke Street between Spring Street and Exhibi...,3.37,2021-04-30,321421.98,5813108.43,2021-08-14,"-37.81196859547474, 144.97129539621886"
3,1078910,Seat - Handrail Steps and Seating Wall,Outdoor Furniture,Seat,201101-011,Seat - Handrail Steps and Seating Wall,Infrastructure and Assets,City of Melbourne,Bourke Street between Swanston Street and Eliz...,3.45,2021-04-30,320726.63,5812852.83,2021-08-14,"-37.81413462369066, 144.96333729992477"
4,1078950,Seat - Metal Semi-circular Seats,Outdoor Furniture,Seat,201101-021,Seat - Metal Semi-circular Seats,Infrastructure and Assets,City of Melbourne,Grattan Street between Lygon Street and Cardig...,3.11,2021-04-30,320969.66,5814340.01,2021-08-14,"-37.80078654068136, 144.96646421301875"

In [100]:
print("Rows and columns:", furn.shape)

print("\nColumn names:")
print(furn.columns.tolist())

print("\nData types:")
print(furn.dtypes)

print("\nFirst 5 rows:")
display(furn.head())

Rows and columns: (23426, 15)

Column names:
['GIS_ID', 'DESCRIPTION', 'ASSET_CLASS', 'ASSET_TYPE', 'MODEL_NO', 'MODEL_DESCR', 'DIVISION', 'COMPANY', 'LOCATION_DESC', 'CONDITION_RATING', 'EVALUATION_DATE', 'EASTING', 'NORTHING', 'UploadDate', 'CoordinateLocation']

Data types:
GIS_ID                  int64
DESCRIPTION            object
ASSET_CLASS            object
ASSET_TYPE             object
MODEL_NO               object
MODEL_DESCR            object
DIVISION               object
COMPANY                object
LOCATION_DESC          object
CONDITION_RATING      float64
EVALUATION_DATE        object
EASTING               float64
NORTHING              float64
UploadDate             object
CoordinateLocation     object
dtype: object

First 5 rows:

,GIS_ID,DESCRIPTION,ASSET_CLASS,ASSET_TYPE,MODEL_NO,MODEL_DESCR,DIVISION,COMPANY,LOCATION_DESC,CONDITION_RATING,EVALUATION_DATE,EASTING,NORTHING,UploadDate,CoordinateLocation
0,1078671,Floral Crate/Planter Box - Granite Tree Plante...,Outdoor Furniture,Floral Crate/Planter Box,200601-001,Floral Crate/Planter Box - Granite Tree Plante...,Infrastructure and Assets,City of Melbourne,Bourke Street between Swanston Street and Eliz...,3.45,2021-04-30,320850.60,5812901.23,2021-08-14,"-37.8137229993323, 144.9647568363893"
1,1084271,Bollard - Timber Bollard,Outdoor Furniture,Bollard,200401-067,Bollard - Timber Bollard,Infrastructure and Assets,City of Melbourne,St Kilda Road between Armadale Street and Comm...,2.85,2021-04-30,322159.31,5809533.16,2021-08-14,"-37.8443169308817, 144.9787883061352"
2,1078893,Seat - Stainless Steel Straight Seat,Outdoor Furniture,Seat,201101-027,Seat - Stainless Steel Straight Seat,Infrastructure and Assets,City of Melbourne,Bourke Street between Spring Street and Exhibi...,3.37,2021-04-30,321421.98,5813108.43,2021-08-14,"-37.81196859547474, 144.97129539621886"
3,1078910,Seat - Handrail Steps and Seating Wall,Outdoor Furniture,Seat,201101-011,Seat - Handrail Steps and Seating Wall,Infrastructure and Assets,City of Melbourne,Bourke Street between Swanston Street and Eliz...,3.45,2021-04-30,320726.63,5812852.83,2021-08-14,"-37.81413462369066, 144.96333729992477"
4,1078950,Seat - Metal Semi-circular Seats,Outdoor Furniture,Seat,201101-021,Seat - Metal Semi-circular Seats,Infrastructure and Assets,City of Melbourne,Grattan Street between Lygon Street and Cardig...,3.11,2021-04-30,320969.66,5814340.01,2021-08-14,"-37.80078654068136, 144.96646421301875"

In [101]:
miss = pd.DataFrame({
    "missingcount": furn.isna().sum(),
    "missingpercent": furn.isna().mean() * 100
}).sort_values("missingpercent", ascending=False)

display(miss)

                    missingcount  missingpercent
EVALUATION_DATE             1310        5.592077
CONDITION_RATING            1310        5.592077
MODEL_DESCR                  379        1.617860
DIVISION                     340        1.451379
COMPANY                      313        1.336122
LOCATION_DESC                101        0.431145
MODEL_NO                      15        0.064031
ASSET_TYPE                     0        0.000000
GIS_ID                         0        0.000000
DESCRIPTION                    0        0.000000
ASSET_CLASS                    0        0.000000
EASTING                        0        0.000000
NORTHING                       0        0.000000
UploadDate                     0        0.000000
CoordinateLocation             0        0.000000

In [102]:
dups = furn.duplicated().sum()

print("Duplicate rows:", dups)

Duplicate rows: 0

In [103]:
types = furn["ASSET_TYPE"].value_counts(
    dropna=False
)

display(types)

ASSET_TYPE
Bollard                     9388
Bicycle Rails               5900
Seat                        3389
Litter Bin                  3294
Tree Guard                   450
Drinking Fountain            302
Floral Crate/Planter Box     206
Hoop                         202
Picnic Setting               170
Barbeque                      63
Information Pillar            43
Horse Trough                  19
Name: count, dtype: int64

In [104]:
core = [
    "Seat",
    "Drinking Fountain",
    "Picnic Setting"
]

extra = [
    "Barbeque",
    "Information Pillar"
]

In [105]:
extra_fac = furn[
    furn["ASSET_TYPE"].isin(extra)
].copy()

print("Extra facilities:", len(extra_fac))

print(
    extra_fac["ASSET_TYPE"].value_counts()
)

Extra facilities: 106
ASSET_TYPE
Barbeque              63
Information Pillar    43
Name: count, dtype: int64

In [106]:
cord = furn["CoordinateLocation"].str.split(
    ",",
    expand=True
)

furn["lat"] = pd.to_numeric(
    cord[0].str.strip(),
    errors="coerce"
)

furn["lon"] = pd.to_numeric(
    cord[1].str.strip(),
    errors="coerce"
)

display(
    furn[
        [
            "ASSET_TYPE",
            "DESCRIPTION",
            "CoordinateLocation",
            "lat",
            "lon"
        ]
    ].head()
)

,ASSET_TYPE,DESCRIPTION,CoordinateLocation,lat,lon
0,Floral Crate/Planter Box,Floral Crate/Planter Box - Granite Tree Plante...,"-37.8137229993323, 144.9647568363893",-37.813723,144.964757
1,Bollard,Bollard - Timber Bollard,"-37.8443169308817, 144.9787883061352",-37.844317,144.978788
2,Seat,Seat - Stainless Steel Straight Seat,"-37.81196859547474, 144.97129539621886",-37.811969,144.971295
3,Seat,Seat - Handrail Steps and Seating Wall,"-37.81413462369066, 144.96333729992477",-37.814135,144.963337
4,Seat,Seat - Metal Semi-circular Seats,"-37.80078654068136, 144.96646421301875",-37.800787,144.966464

In [107]:
print("Missing lat:", furn["lat"].isna().sum())
print("Missing lon:", furn["lon"].isna().sum())

print("Latitude:", furn["lat"].min(), "to", furn["lat"].max())
print("Longitude:", furn["lon"].min(), "to", furn["lon"].max())

Missing lat: 0
Missing lon: 0
Latitude: -37.85054905912764 to -37.77538385001638
Longitude: 144.90019341111423 to 144.99104779257834

In [108]:
core = [
    "Seat",
    "Drinking Fountain",
    "Picnic Setting"
]

extra = [
    "Barbeque",
    "Information Pillar"
]

keep = core + extra


furniture_clean = furn[
    furn["ASSET_TYPE"].isin(keep)
].copy()


print("Final furniture facilities:", len(furniture_clean))

print(
    furniture_clean["ASSET_TYPE"].value_counts()
)

Final furniture facilities: 3967
ASSET_TYPE
Seat                  3389
Drinking Fountain      302
Picnic Setting         170
Barbeque                63
Information Pillar      43
Name: count, dtype: int64

In [109]:
display(
    furniture_clean[
        [
        "GIS_ID",
        "ASSET_TYPE",
        "DESCRIPTION",
        "LOCATION_DESC",
        "CONDITION_RATING",
        "EVALUATION_DATE",
        "lat",
        "lon"
        ]
    ].head(30)
)

,GIS_ID,ASSET_TYPE,DESCRIPTION,LOCATION_DESC,CONDITION_RATING,EVALUATION_DATE,lat,lon
2,1078893,Seat,Seat - Stainless Steel Straight Seat,Bourke Street between Spring Street and Exhibi...,3.37,2021-04-30,-37.811969,144.971295
3,1078910,Seat,Seat - Handrail Steps and Seating Wall,Bourke Street between Swanston Street and Eliz...,3.45,2021-04-30,-37.814135,144.963337
4,1078950,Seat,Seat - Metal Semi-circular Seats,Grattan Street between Lygon Street and Cardig...,3.11,2021-04-30,-37.800787,144.966464
6,1078970,Seat,Seat - Metal Seat,Exhibition Street between Little Collins Stree...,3.13,2021-04-30,-37.812358,144.970545
8,1079075,Seat,Seat - Metal Bench,Victoria Parade between Powlett Street and Cla...,1.00,2021-04-30,-37.809464,144.984814
10,1079129,Seat,Seat - Metal Bench,Flinders Street between William Street and Kin...,3.17,2021-04-30,-37.819786,144.958976
13,1079162,Seat,Seat - Metal Seat,Bourke Street between Elizabeth Street and Que...,3.16,2021-04-30,-37.814515,144.961910
14,1079163,Seat,Seat - Metal Seat,"Tramways Signal Cabin, Shelter and Convenience...",3.01,2021-04-30,-37.806792,144.962678
15,1079236,Seat,Seat - Metal Seat,Coventry Street between Dodds Street and Sturt...,2.99,2021-04-30,-37.830348,144.965744
16,1079265,Seat,Seat - Metal Seat,Victoria Parade between Clarendon Street and E...,2.96,2021-04-30,-37.809101,144.981527
18,1079340,Seat,Seat - Metal Seat,Queensberry Street between Curzon Street and A...,3.05,2021-04-30,-37.802756,144.945909
20,1079387,Seat,Seat - Metal Seat,Queen Street between Lonsdale Street and Littl...,3.11,2021-04-30,-37.812725,144.959805
22,1079396,Seat,Seat - Metal Seat,Collins Street between Elizabeth Street and Qu...,3.17,2021-04-30,-37.816417,144.963710
23,1079400,Seat,Seat - Metal Seat,Leicester Street between Queensberry Street an...,2.95,2021-04-30,-37.803976,144.960483
25,1079446,Seat,Seat - Metal Seat,Southbank Promenade approximately 14m SW of Lw...,3.16,2021-04-30,-37.820081,144.965308
26,1079450,Seat,Seat - Metal Seat,Southbank Promenade approximately 15m East of ...,3.16,2021-04-30,-37.820027,144.965593
27,1079465,Seat,Seat - Metal Seat,Riverside Avenue between St Kilda Road and Sou...,3.16,2021-04-30,-37.819821,144.967001
28,1079468,Seat,Seat - Metal Seat,Lygon Street between Victoria Street and Queen...,3.08,2021-04-30,-37.806328,144.965827
29,1079484,Seat,Seat - Metal Seat,Victoria Street between O'Connell Street and C...,3.16,2021-04-30,-37.806152,144.957353
30,1079491,Seat,Seat - Metal Seat,Bourke Street between Elizabeth Street and Que...,3.16,2021-04-30,-37.814918,144.961224
31,1079493,Seat,Seat - Metal Seat,King Street between Little Lonsdale Street and...,3.12,2021-04-30,-37.813220,144.954408
32,1079498,Seat,Seat - Metal Seat,Gisborne Street between Albert Street and Vict...,2.16,2021-04-30,-37.808787,144.975594
33,1079502,Seat,Seat - Metal Seat,Albert Street between Nicholson Street and Gis...,3.16,2021-04-30,-37.809375,144.975128
34,1079513,Seat,Seat - Metal Seat,Southbank Promenade approximately 45m East of ...,3.16,2021-04-30,-37.820535,144.963537
35,1079516,Seat,Seat - Metal Seat,Southbank Promenade approximately 61m East of ...,2.16,2021-04-30,-37.820418,144.963715
37,1079550,Seat,Seat - Metal Seat,Dodds Street between Miles Street and Grant St...,2.99,2021-04-30,-37.828156,144.967208
38,1079564,Seat,Seat - Metal Seat,Weedon Reserve approximately 15m North of 43 W...,2.94,2021-04-30,-37.817359,144.988578
39,1079572,Seat,Seat - Metal Seat,Approximately 33m NE of Town Hall Rail Station...,3.16,2021-04-30,-37.816875,144.967380
40,1079585,Seat,Seat - Metal Seat,Barkly Street between Nicholson Street and Can...,2.92,2021-04-30,-37.798074,144.974522
42,1079618,Seat,Seat - Metal Seat,Gisborne Street between Albert Street and Vict...,3.16,2021-04-30,-37.808576,144.976125

In [110]:
print(
    furniture_clean["CONDITION_RATING"].describe()
)

print(
    furniture_clean["CONDITION_RATING"].isna().sum()
)

count    3966.000000
mean        3.419420
std         0.792112
min         1.000000
25%         3.000000
50%         3.395000
75%         4.000000
max         5.000000
Name: CONDITION_RATING, dtype: float64
1

In [111]:
lowc = furniture_clean[
    furniture_clean["CONDITION_RATING"].notna()
    &
    (furniture_clean["CONDITION_RATING"] < 2)
].copy()

print("Low condition facilities:", len(lowc))

display(
    lowc[
        [
            "ASSET_TYPE",
            "DESCRIPTION",
            "LOCATION_DESC",
            "CONDITION_RATING"
        ]
    ].head(20)
)

Low condition facilities: 184

,ASSET_TYPE,DESCRIPTION,LOCATION_DESC,CONDITION_RATING
8,Seat,Seat - Metal Bench,Victoria Parade between Powlett Street and Cla...,1.00
58,Seat,Seat - Metal Seat,"Approximately 36m East of Yarra Botanicals, Sa...",1.16
60,Seat,Seat - Metal Seat,St Augustines Church approximately 45m South o...,1.00
65,Seat,Seat - Straight Seat - Wooden Battens - Type 2,Enterprize Park approximately 57m SE of Enterp...,1.00
66,Seat,Seat - Straight Seat - Wooden Battens - Type 2,Enterprize Park approximately 58m SE of Enterp...,1.00
273,Seat,Seat - Metal Bench,Godfrey Street between Bourke Street and Littl...,1.93
294,Seat,Seat - Handrail Steps and Seating Wall,Bourke Street between Swanston Street and Eliz...,1.45
349,Seat,Seat - Stainless Steel Straight Seat,Russell Street between Collins Street and Litt...,1.42
564,Seat,Seat - Flat Bench Seat - L Shaped,Royal Parade between Grattan Street and Story ...,1.17
1461,Seat,Seat - Flat Bench Seat - L Shaped,Grattan Street between Flemington Road and Eli...,1.00
1666,Seat,Seat - Straight Seat - Wooden Battens,Kings Domain South approximately 54m NE of Car...,1.00
1667,Drinking Fountain,Drinking Fountain - Stainless Steel Drinking F...,Collins Street between Russell Street and Swan...,1.45
1773,Seat,Seat - Metal Seat - Kensington Banks Type,The Crescent between Mercantile Parade and Gat...,1.59
1774,Seat,Seat - Metal Seat - Kensington Banks Type,The Crescent between Mercantile Parade and Gat...,1.59
1775,Seat,Seat - Metal Seat - Kensington Banks Type,The Crescent between Mercantile Parade and Gat...,1.59
1989,Drinking Fountain,Drinking Fountain - Duke & Duchess of York Mem...,Elizabeth Street between Therry Street and Vic...,1.26
2043,Seat,Seat - Metal Seat,Epsom Road between Kensington Road and The Rid...,1.00
2059,Seat,Seat - Straight Seat - Wooden & Concrete,St Augustines Church approximately 28m East of...,1.00
2063,Seat,Seat - Straight Seat - Wooden Battens - Type 2,Kings Domain South approximately 63m SE of The...,1.39
2064,Seat,Seat - Straight Seat - Wooden Battens - Type 2,Enterprize Park approximately 57m South of Ent...,1.00

In [112]:
def condition_category(x):
    if x >= 4:
        return "Good"
    elif x >= 2:
        return "Average"
    else:
        return "Poor"


furniture_clean["CONDITION_CATEGORY"] = (
    furniture_clean["CONDITION_RATING"]
    .apply(condition_category)
)


print(
    furniture_clean["CONDITION_CATEGORY"].value_counts()
)

CONDITION_CATEGORY
Average    2294
Good       1488
Poor        185
Name: count, dtype: int64

In [113]:
furniture_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3967 entries, 2 to 23421
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   GIS_ID              3967 non-null   int64
 1   DESCRIPTION         3967 non-null   object
 2   ASSET_CLASS         3967 non-null   object
 3   ASSET_TYPE          3967 non-null   object
 4   MODEL_NO            3956 non-null   object
 5   MODEL_DESCR         3865 non-null   object
 6   DIVISION            3962 non-null   object
 7   COMPANY             3965 non-null   object
 8   LOCATION_DESC       3915 non-null   object
 9   CONDITION_RATING    3966 non-null   float64
 10  EVALUATION_DATE     3966 non-null   object
 11  EASTING             3967 non-null   float64
 12  NORTHING            3967 non-null   float64
 13  UploadDate          3967 non-null   object
 14  CoordinateLocation  3967 non-null   object
 15  lat                 3967 non-null   float64
 16  lon                 3967 non-null   float64
 17  CONDITION_CATEGORY  3967 non-null   object
dtypes: float64(5), int64(1), object(12)
memory usage: 588.9+ KB

In [114]:
furniture_clean.to_csv(
    "street_furniture_clean.csv",
    index=False
)